<?php 
//include('../header.php'); //parent content 
include('../../header.php'); //sub content 
?>

<main class="boxed">
<div class="grid-container">
	<div class="row"> 
		<div class="columns small-12 medium-8">
<!-- do not copy above this line -->
<h2>Background</h2>

<p>Accounts Division was established on September 2006, as a Self Accouting Department in accordance with Treasury Instruction 139. In ensuring Accounts Division undertake its responsibilities efficiently and effectively, the division is divided into four main functions namely Payment Management, Accounts, Payroll, Consultation and two other general functions namely Information Technology and Administration. </p>

<h2>Client's Charter </h2>

<p>In our effort to improve public system delivery and provide excellent accounting services, we promise to:</p>

<ul><li>Process payments within 4 calendar days from the date of payment vouchers received.</li>
<li>Credit monthly salary for administration officers and government personnel under the ministry on every 25th day of the month or earlier date as stipulated by the federal government.</li>
<li>Account for federal government revenues generated by respective departments / agencies and issue official receipts within 3 working days from the date of collector’s statements received.</li>
<li>Process advances, car and computer loan applications made by government personnel under the ministry within 5 working days from the date of application received.</li>
<li>Process invalid cheque / eft replacements within 7 working days from the date of request received.</li>
<li>Ensure proper AP58(a) certificates submitted by departments / agencies are approved in 1 working day upon receipt of the certificates.</li>
<li>Provide monthly accounting reports for departments / agencies by the 5th day of the following month.</li>
<li>Review working papers on new payment and collection systems prepared by department / agencies in 30 days from the date of submission.</li>
<li>Provide explanatory answers on audit queries within 14 working days from the date of query received.</li>
<li>Provide departments / agencies advisory and consultancy services in relation to public accounting and finance matters within 3 working days from the date of inquiry received.​</li></ul>

<h2>Functions </h2>

<h3>Mangement Accounting Section</h3>

<p>To provide relevant information and reports in assisting top management in decision making on the following matters:</p>

<ul><li>Provide costs information to evaluate Ministrial programs executed under the Outcome Based Budgeting (OBB) and other cost related information needed for management references.</li>
<li>Prepare Cost Analysis to be used by mangement for monitoring purposes.</li>
<li>Prepare Financial Analysis and reports for top management to make decision.</li>
<li>Analyse and provide information on assets, liabilities and other commitments of the Ministry for financial planning preparation.</li></ul>

<h3>Finance Accounting Section</h3>

<p>To ensure financial information as below is prepared correctly and timely:</p>

<ul><li>Verify Payroll Changes Forms (SG20)</li>
<li>Manage revenues / account receivables</li>
<li>Manage payments / account payables</li>
<li>Perform bulk payments to agencies </li>
<li>Provide technical assistance to Responsibility Centers on operational issues​​</li>
<li>Prepare accounting operatios analysis for management monitoring purposes </li>
<li>Manage Subsidiary Account/Ledgers</li>
<li>Manage Imprest AccountsManage Trust Accounts</li>
<li>Manage Deposit Accounts</li>
<li>Prepare month end / year end Financial Statements of the Ministry</li>
<li>Provide bank reconciliation for Ministry Receipts and Payment Accounts</li>
<li>Manage cheque / telegraphic transfer and EFT rejection / cancelled cheque </li>
<li>Manage accounting for capital assets and inventories</li>
<li>Manage accounting for other assets and liabilities</li>
<li>Prepare Accounting Assets Report at Ministry Level </li>
<li>Prepare analysis of asset useful life and recommendation of asset disposal/replacement for management</li></ul>

<h3>Consultation Section</h3>
<p>To provide consultancy on financial and management accounting and application of accounting systems as follows:</p>

<ul><li>Consult Responsibility Centers on financial and management accounting matters.</li>
<li>Consult and monitor the implementation of accounting system at department and 1GFMAS agencies under the ministry</li>
<li>Prepare analysis on consultation issues for management to decide on follow up actions</li>
<li>Provide expert opinions and problem solving solutions related to accrual accounting issues</li>
<li>Plan and organize trainings on accounting programs to produce competent staffs</li>
<li>Ensure all accounting officers undergo trainings and continuous development programs for technical skill and knowledge enhancement</li>
<li>Prepare post training analysis to evaluate on the program's effectiveness towards participants.</li></ul>

<h3>Monitoring Section</h3>

<p>To monitor compliance and verification on financial and management accounting practices in the Ministry as follows:​</p>

<ul><li>Perform Compliance Audit</li>
<li>Perform Receipting Compliance Audit</li>
<li>Perform Revenue Collection Verification</li>
<li>Perform Assets Verification</li>
<li>Perform Trust and Deposit Accounts Verification</li>
<li>Prepare analysis on compiance and verification issues for management review</li>
<li>Implement Financial Risk Management Monitoring of Accounts Receivables at Collection Centers</li>
<li>Monitoring of Accounts Payabale records at Responsibilty Centers</li></ul>

<h3>Administration And Finance Unit</h3>

<p>Manage divisional administrative and financial matters </p>

<ul><li>Perform administrative affairs</li>
<li>Perform financial functions</li>
<li>Handle store and assets mattersHandle staffs and service matters</li>
<li>Prepare financial analysis on budget and spending for management review </li></ul>

<h2>Objectives </h2>

<ul><li>To ensure efficient, effective and sound accounting system in Ministry of Transport.</li>
<li>To monitor the revenue or trust receipts of Federal Government and to take necessary steps in ensuring that the revenue or trust is collected timely.</li>
<li>To ensure that only authorized expenses are charged and recorded in the accounts accordingly.</li>
<li>To report to the Ministry’s Secretary General any material irregularity related to the accounts under his/her jurisdiction.​</ul></li>

<h2>Organisation​ Chart​ ​</h2>
<a class="light-box" href="cartaakaunbi.jpg">
	<img class="light-box" src="cartaakaunbi.jpg" />
</a>


<!-- do not copy BELOW this line -->
		</div>
		<div class="columns small-12 medium-4">
			<?php include('division-sidebar.php')?>
		</div>
	</div>
 </div>
</main>
<?php 
//include('../footer.php'); //parent content
include('../../footer.php'); //sub content ?> 
